# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# mkdocs:
# configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
# python:
#   install:
#   - requirements: docs/requirements.txt

# Reference: https://docs.readthedocs.io/en/latest/yaml-config.html

#build:
#  image: latest

# Possible options: htmlzip, pdf, epub
# Disable (single) htmlzip as it's way too big to be useful,
# and leads to excessive memory usage on build
# Disable epub and pdf for now to speed up builds
# formats:
#   - pdf
